---
apiVersion: v1
kind: Service
metadata:
  name: randomapp
  labels:
    name: randomapp
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: randomapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: randomapp
  labels:
    name: randomapp
    app: randomapp
spec:
  selector:
    matchLabels:
      app: randomapp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: randomapp
        app: randomapp
    spec:
      terminationGracePeriodSeconds: 30
      hostname: randomapphost
      containers:
      - name: randomapp
        image: ruiztulio/randomapp
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: randomapp-db
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: randomapp-config
                key: db_password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: randomapp-config
                key: db_user
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: randomapp-config
                key: db_name

        ports:
        - name: randomapp
          containerPort: 8000
