apiVersion: v1
kind: Secret
metadata:
  name: randomapp-config
type: Opaque
data:
  db_password: WnVwM3JTM2N1ckVQNHp6
  db_user: cmFuZG9tYXBwdXNlcg==
  db_name: cmFuZG9tYXBw
  postgresq_pass: WU1ZNzJQOXpld1Z1UlRSRlpIVnFkSjVyVDRreXQ2cUxVZDNC
  populate_db: b3JpZ2lu
  populate_user: b3JpZ2ludXNlcg==
  populate_pass: U3I0OXk3MnVkOE1UY1F3ZEI5ZnVVZjJCNmF5R2Q=


