apiVersion: v1
kind: Secret
metadata:
  name: randomapp-config
type: Opaque
data:
  db_password: WnVwM3JTM2N1ckVQNHp6
  db_user: cmFuZG9tYXBwdXNlcg==
  db_name: cmFuZG9tYXBw
  postgresq_pass: WU1ZNzJQOXpld1Z1UlRSRlpIVnFkSjVyVDRreXQ2cUxVZDNC
  

