# Generated by Django 2.0.3 on 2018-03-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='worker_id',
            field=models.UUIDField(default=None),
        ),
    ]
