# Generated by Django 2.0.3 on 2018-03-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0002_userdata_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='worker_id',
            field=models.UUIDField(null=True),
        ),
    ]
