# Generated by Django 2.0.3 on 2018-03-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0003_auto_20180320_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
